
data:
  root_dir: "/shared/home/lvanderpeet/subaps/sbs"

  train:
    tensor_dir: "out_tensors_train_x96"
    csv: "out_tensors_train_x96/train_metadata_x96.csv"
    image_size: 96
    batch_size: 128
    num_workers: 8

  valid:
    tensor_dir: "out_tensors_valid_x96"
    csv: "out_tensors_valid_x96/valid_metadata_x96.csv"

  normalization:
    type: "percentile"
    stats_file: "/shared/home/lvanderpeet/percentiles_sm.npy"

  subaperture_config:
    input_indices: [1,2]
    output_indices: [3]

model:
  name: "unet"
  in_channels: 2
  out_channels: 2
  base_channels: 64
  depth: 4

training:
  epochs: 50
  learning_rate: 0.0002
  optimizer: "adamw"
  weight_decay: 0.01
  save_dir: "./experiments/"
  device: "cuda"
  checkpoint_interval: 5

